# Generated by Django 3.0.2 on 2020-01-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=16)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50, unique=True)),
                ('recipe_description', models.CharField(max_length=500)),
                ('recipe_ingredients', models.CharField(max_length=500)),
                ('recipe_steps', models.CharField(max_length=2000)),
                ('recipe_img', models.ImageField(upload_to='images/')),
                ('recipe_publish', models.DateField()),
                ('recipe_edit', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstuffs.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstuffs.User')),
                ('userrecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstuffs.UserRecipe')),
            ],
        ),
    ]
